name: React Application CI/CD

on:
  push:
    branches: [ master ]

jobs:
  buildAndTest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM packages
        run: npm install
      - name: Call npm test
        run: npm test
      - name: Build for productive
        run: npm run build
      - name: Put built assets in Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: build
