name: React Application CI/CD

on:
  push:
    branches: [ deploy ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
#    runs-on: ubuntu-latest
    runs-on: self-hosted

    strategy:
      matrix:
#        node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm test
      - run: npm run build
      - run: mv /home/michi/actions-runner/actions-runner/cicd-example/cicd-example/build /var/www/html
