name: React Application CI/CD

on:
  push:
    branches: [ master ]

jobs:
  buildAndTest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
#      - name: Install NPM packages
#        run: npm install
#      - name: Call npm test
#        run: npm test
#      - name: Build for productive
#        run: npm run build
      - name: Dummy data
        run: cd /home/lukas/actions-runner-react/_work/cicd-example/cicd-example/ && mkdir build && cd build && touch dummy.txt
      - name: Put built assets in Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: build
  deploy-production:
    name: Deploy Project to PRODUCTION Server
    runs-on: self-hosted
    needs: [buildAndTest]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch built assets from Artifacts
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: build
      - name: Setup Deployer
        uses: mleister97/deployer-php-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Deploy to PRODUCTION Server
        run: dep deploy production --tag=${{ env.GITHUB_REF }} -vvv
